// <auto-generated />
using System;
using Lesson8_EF_SP_Join.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson8_EF_SP_Join.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lesson8_EF_SP_Join.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifierDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laptop computers",
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mobile smartphones",
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tablet computers",
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer monitors",
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer keyboards",
                            Name = "Keyboards"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer mice",
                            Name = "Mice"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Audio headphones",
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Digital cameras",
                            Name = "Cameras"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Office printers",
                            Name = "Printers"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer accessories",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("Lesson8_EF_SP_Join.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifierDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell Inspiron 15",
                            Price = 1450.00m,
                            SupplierId = 1,
                            UnitInStock = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HP Pavilion 15",
                            Price = 1350.00m,
                            SupplierId = 2,
                            UnitInStock = 12
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S24",
                            Price = 1850.00m,
                            SupplierId = 3,
                            UnitInStock = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iPhone 15",
                            Price = 2100.00m,
                            SupplierId = 4,
                            UnitInStock = 18
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iPad Air",
                            Price = 1650.00m,
                            SupplierId = 5,
                            UnitInStock = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy Tab S9",
                            Price = 1450.00m,
                            SupplierId = 6,
                            UnitInStock = 14
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LG UltraGear 27",
                            Price = 850.00m,
                            SupplierId = 7,
                            UnitInStock = 9
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Odyssey G5",
                            Price = 920.00m,
                            SupplierId = 8,
                            UnitInStock = 11
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logitech K380",
                            Price = 75.00m,
                            SupplierId = 9,
                            UnitInStock = 30
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Redragon K552",
                            Price = 95.00m,
                            SupplierId = 10,
                            UnitInStock = 25
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logitech MX Master 3S",
                            Price = 180.00m,
                            SupplierId = 1,
                            UnitInStock = 17
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer DeathAdder V2",
                            Price = 120.00m,
                            SupplierId = 2,
                            UnitInStock = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony WH-1000XM5",
                            Price = 650.00m,
                            SupplierId = 3,
                            UnitInStock = 13
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "JBL Tune 770NC",
                            Price = 220.00m,
                            SupplierId = 4,
                            UnitInStock = 27
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon EOS 250D",
                            Price = 1750.00m,
                            SupplierId = 5,
                            UnitInStock = 7
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon D7500",
                            Price = 2300.00m,
                            SupplierId = 6,
                            UnitInStock = 6
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HP LaserJet Pro",
                            Price = 480.00m,
                            SupplierId = 7,
                            UnitInStock = 8
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon Pixma G3410",
                            Price = 390.00m,
                            SupplierId = 8,
                            UnitInStock = 10
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anker USB-C Hub",
                            Price = 85.00m,
                            SupplierId = 9,
                            UnitInStock = 35
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Baseus Laptop Stand",
                            Price = 65.00m,
                            SupplierId = 10,
                            UnitInStock = 40
                        });
                });

            modelBuilder.Entity("Lesson8_EF_SP_Join.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifierDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Baku, Nizami Street 10",
                            CompanyName = "TechWorld LLC",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994501112233"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Baku, Tbilisi Avenue 25",
                            CompanyName = "Global Electronics",
                            CreatedDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994502223344"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Baku, Yasamal District 15",
                            CompanyName = "Smart Solutions",
                            CreatedDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994503334455"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Baku, Narimanov 30",
                            CompanyName = "Digital Store",
                            CreatedDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994504445566"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Baku, Khatai 12",
                            CompanyName = "Future Tech",
                            CreatedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994505556677"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Baku, Genclik 18",
                            CompanyName = "Electro Market",
                            CreatedDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994506667788"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Baku, Sahil 22",
                            CompanyName = "Max Electronics",
                            CreatedDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994507778899"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Baku, 28 May 14",
                            CompanyName = "Azerbaijan Tech",
                            CreatedDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994508889900"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Baku, Ahmadli 40",
                            CompanyName = "Next Generation",
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994509990011"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Baku, Badamdar 8",
                            CompanyName = "Prime Suppliers",
                            CreatedDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+994510001122"
                        });
                });

            modelBuilder.Entity("Lesson8_EF_SP_Join.Models.Product", b =>
                {
                    b.HasOne("Lesson8_EF_SP_Join.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lesson8_EF_SP_Join.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lesson8_EF_SP_Join.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lesson8_EF_SP_Join.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
